#!/usr/bin/env node
/* Copy export queue from stdin JSON or file into js/generated-part-builds.js
   Usage: node asseteditor/apply-export.mjs path/to/export-queue.json */
'use strict';
const fs = require('fs');
const path = require('path');

const inPath = process.argv[2];
if (!inPath) {
  console.error('Usage: node asseteditor/apply-export.mjs <queue.json>');
  process.exit(1);
}
const queue = JSON.parse(fs.readFileSync(inPath, 'utf8'));
const out = `/* AUTO-GENERATED by NOVA Asset Editor — ${new Date().toISOString()}\n   Replaces part meshes at runtime via part-overrides.js */\n'use strict';\nwindow.NSP_PART_OVERRIDES = ${JSON.stringify(queue, null, 2)};\n`;
const dest = path.join(__dirname, '..', 'js', 'generated-part-builds.js');
fs.writeFileSync(dest, out);
console.log('Wrote', dest, '(' + Object.keys(queue).length, 'parts)');
